import { rgb } from 'pdf-lib';
import { ICoordinates } from '../interfaces/coordinates.interface';
import { GenerateTemplateDto } from '../dto/generate-template.dto';
import { formatDate } from '../../../common/utils/formatDate';

export const buildDelayTemplateDataUtil = (
    dto: GenerateTemplateDto,
): ICoordinates[] => {
    return [
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 12,
            text: dto.passengerName,
            x: 290,
            y: 627,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 422,
            y: 594,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.signedAt, 'dd.mm.yyyy'),
            x: 482,
            y: 594,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 335,
            y: 434,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date, 'dd.mm.yyyy'),
            x: 401,
            y: 434,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 214,
            y: 406,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 250,
            y: 349,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 319,
            y: 336,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 108,
            y: 336,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date, 'dd.mm.yyyy'),
            x: 138,
            y: 321,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 154,
            y: 282,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 374,
            y: 255,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 167,
            y: 230,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 101,
            y: 204,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date, 'dd.mm.yyyy'),
            x: 244,
            y: 177,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 374,
            y: 137,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date, 'dd.mm.yyyy'),
            x: 297,
            y: 555,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 200,
            y: 572,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 314,
            y: 572,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 72,
            y: 556,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.signedAt, 'dd.mm.yyyy'),
            x: 176,
            y: 493,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 223,
            y: 477,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(new Date()),
            x: 466,
            y: 198,
            fontWeight: 'BOLD',
        },
    ];
};
