import { rgb } from 'pdf-lib';
import { ICoordinates } from '../interfaces/coordinates.interface';
import { GenerateTemplateDto } from '../dto/generate-template.dto';
import { formatDate } from '../../../common/utils/formatDate';

export const buildOverbookingTemplateDataUtil = (
    dto: GenerateTemplateDto,
): ICoordinates[] => {
    return [
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 12,
            text: dto.passengerName,
            x: 290,
            y: 599,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 422,
            y: 566,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 482,
            y: 566,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 342,
            y: 406,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 419,
            y: 406,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 214,
            y: 378,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 108,
            y: 322,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 243,
            y: 322,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 107,
            y: 308,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 342,
            y: 308,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 154,
            y: 254,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 380,
            y: 228,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 169,
            y: 202,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 101,
            y: 176,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 242,
            y: 150,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 99,
            y: 80,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 175,
            y: 431,
            fontWeight: 'BOLD',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 224,
            y: 414,
            fontWeight: 'BOLD',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(new Date()),
            x: 466,
            y: 136,
            fontWeight: 'BOLD',
        },
    ];
};
