import { rgb } from 'pdf-lib';
import { ICoordinates } from '../interfaces/coordinates.interface';
import { GenerateTemplateDto } from '../dto/generate-template.dto';
import { formatDate } from '../../../utils/formatDate';

export const buildDelayTemplateDataUtil = (
    dto: GenerateTemplateDto,
): ICoordinates[] => {
    return [
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 12,
            text: dto.passengerName,
            x: 290,
            y: 599,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 422,
            y: 566,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 482,
            y: 566,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 335,
            y: 406,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 401,
            y: 406,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 214,
            y: 378,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 248,
            y: 322,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: `${dto.departureAirport}(D)`,
            x: 107,
            y: 308,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: `${dto.arrivalAirport}(A)`,
            x: 320,
            y: 308,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 138,
            y: 294,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 154,
            y: 254,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 370,
            y: 228,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: `${dto.departureAirport}(D)`,
            x: 169,
            y: 202,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 101,
            y: 176,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 244,
            y: 149,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: `${dto.departureAirport}(D)`,
            x: 74,
            y: 81,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 210,
            y: 448,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: `${dto.departureAirport}(D)`,
            x: 343,
            y: 448,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: `${dto.arrivalAirport}(A)`,
            x: 73,
            y: 432,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 299,
            y: 432,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 177,
            y: 369,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 223,
            y: 353,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: new Date().getDate().toString().padStart(2, '0'),
            x: 465,
            y: 59,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: (new Date().getMonth() + 1).toString().padStart(2, '0'),
            x: 481,
            y: 59,
            fontWeight: 'REGULAR',
        },
    ];
};
