import { rgb } from 'pdf-lib';
import { ICoordinates } from '../interfaces/coordinates.interface';
import { GenerateTemplateDto } from '../dto/generate-template.dto';
import { formatDate } from '../../../utils/formatDate';

export const buildDelayTemplateDataUtil = (
    dto: GenerateTemplateDto,
): ICoordinates[] => {
    return [
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 12,
            text: dto.passengerName,
            x: 290,
            y: 626,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 422,
            y: 593,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 482,
            y: 593,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 335,
            y: 434,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 401,
            y: 434,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 214,
            y: 406,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 248,
            y: 349,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 107,
            y: 335,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 320,
            y: 335,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 138,
            y: 321,
            fontWeight: 'BOLD',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.passengerName,
            x: 154,
            y: 281,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 380,
            y: 255,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 169,
            y: 229,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 101,
            y: 203,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 244,
            y: 177,
            fontWeight: 'REGULAR',
        },
        {
            page: 1,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 373,
            y: 137,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.flightNumber,
            x: 198,
            y: 493,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.departureAirport,
            x: 315,
            y: 493,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.arrivalAirport,
            x: 73,
            y: 476,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 299,
            y: 476,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: formatDate(dto.date),
            x: 177,
            y: 414,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: dto.claimId,
            x: 223,
            y: 398,
            fontWeight: 'REGULAR',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: new Date().getDate().toString().padStart(2, '0'),
            x: 465,
            y: 119,
            fontWeight: 'BOLD',
        },
        {
            page: 2,
            color: rgb(0, 0, 0),
            size: 10.5,
            text: (new Date().getMonth() + 1).toString().padStart(2, '0'),
            x: 480,
            y: 119,
            fontWeight: 'BOLD',
        },
    ];
};
